apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clients-pod-editor
  namespace: clients
subjects:
  - kind: User
    name: devops
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: clients-pod-editor
  apiGroup: rbac.authorization.k8s.io